'use strict';

// agents/pr-creator.js - GitHub PR Creator
//
// Reads improvements from reports/{site}-improvements-{date}.json and
// creates a GitHub pull request with each improvement as a file edit.
//
// Branch naming: cultivai/{site}-{date}-{shortHash}
// PR title:      [Cultivai] {site} — {date} improvements ({n} changes)
// PR body:       Markdown table of all changes with confidence + source
//
// Uses GitHub REST API v3 via @octokit/rest.

const fs   = require('fs');
const path = require('path');
const { createHash } = require('crypto');

const REPORTS_DIR = path.join(__dirname, '..', 'reports');

function shortHash(input) {
  return createHash('sha256').update(input).digest('hex').slice(0, 7);
}

function todayStr() {
  return new Date().toISOString().slice(0, 10);
}

function buildPrBody(improvements, siteConfig, date) {
  const header = [
    `## Cultivai automated improvements — ${siteConfig.displayName || siteConfig.name} (${date})`,
    '',
    `**${improvements.length} change${improvements.length !== 1 ? 's' : ''}** generated from live GSC, ads, and competitor signals.`,
    '',
    '| Type | File | Selector | Confidence | Sources |',
    '|------|------|----------|------------|---------|',
  ];

  const rows = improvements.map((imp) => {
    const conf    = `${Math.round(imp.confidence * 100)}%`;
    const sources = (imp.source_findings || []).join(', ');
    const file    = imp.file || '—';
    const sel     = imp.selector || '—';
    return `| ${imp.type} | \`${file}\` | \`${sel}\` | ${conf} | ${sources} |`;
  });

  const footer = [
    '',
    '### Change details',
    '',
    ...improvements.map((imp, i) => [
      `#### ${i + 1}. ${imp.type} — \`${imp.file}\``,
      '',
      `**Selector:** \`${imp.selector}\`  `,
      `**Rationale:** ${imp.rationale}  `,
      `**Confidence:** ${Math.round(imp.confidence * 100)}%  `,
      '',
      '**Current:**',
      '```',
      imp.current,
      '```',
      '',
      '**Proposed:**',
      '```',
      imp.proposed,
      '```',
      '',
    ].join('\n')),
    '---',
    '_Generated by [Cultivai](https://github.com/hpierre00/cultivai) — review carefully before merging._',
  ];

  return [...header, ...rows, ...footer].join('\n');
}

function applyImprovement(content, imp) {
  if (!imp.current || !imp.proposed) return content;
  if (content.includes(imp.current)) {
    return content.replace(imp.current, imp.proposed);
  }
  console.warn(`[pr-creator] applyImprovement: exact match not found for selector "${imp.selector}" — skipping`);
  return content;
}

async function getOctokit() {
  const token = process.env.GITHUB_TOKEN || process.env.CULTIVAI_GITHUB_TOKEN;
  if (!token) throw new Error('Missing GITHUB_TOKEN / CULTIVAI_GITHUB_TOKEN env var');
  const { Octokit } = require('@octokit/rest');
  return new Octokit({ auth: token });
}

function parseRepo(repoString) {
  const [owner, repo] = repoString.split('/');
  if (!owner || !repo) throw new Error(`Invalid github_repo format: ${repoString}`);
  return { owner, repo };
}

async function getFileContent(octokit, owner, repo, filePath, ref) {
  try {
    const result = await octokit.repos.getContent({ owner, repo, path: filePath, ref });
    const content = Buffer.from(result.data.content, 'base64').toString('utf-8');
    return { content, sha: result.data.sha };
  } catch (err) {
    if (err.status === 404) return null;
    throw err;
  }
}

async function run(siteConfig, { dryRun = false } = {}) {
  const today    = todayStr();
  const impFile  = path.join(REPORTS_DIR, `${siteConfig.name}-improvements-${today}.json`);

  if (!fs.existsSync(impFile)) {
    console.log(`[pr-creator] No improvements file for ${siteConfig.name} (${today}), skipping.`);
    return { skipped: true };
  }

  const impData     = JSON.parse(fs.readFileSync(impFile, 'utf-8'));
  const improvements = impData.improvements || [];

  if (improvements.length === 0) {
    console.log(`[pr-creator] No improvements to apply for ${siteConfig.name}.`);
    return { skipped: true, reason: 'no_improvements' };
  }

  const hash      = shortHash(`${siteConfig.name}-${today}-${improvements.length}`);
  const branch    = `cultivai/${siteConfig.name}-${today}-${hash}`;
  const prTitle   = `[Cultivai] ${siteConfig.displayName || siteConfig.name} — ${today} improvements (${improvements.length} change${improvements.length !== 1 ? 's' : ''})`;
  const prBody    = buildPrBody(improvements, siteConfig, today);

  if (dryRun) {
    const dryFile = path.join(REPORTS_DIR, `${siteConfig.name}-pr-dryrun-${today}.json`);
    fs.writeFileSync(dryFile, JSON.stringify({ branch, prTitle, prBody, improvements }, null, 2));
    console.log(`[pr-creator] DRY RUN — PR details written to ${dryFile}`);
    return { dryRun: true, branch, prTitle, improvements };
  }

  const outFile = path.join(REPORTS_DIR, `${siteConfig.name}-pr-${today}.json`);
  if (fs.existsSync(outFile)) {
    const existing = JSON.parse(fs.readFileSync(outFile, 'utf-8'));
    console.log(`[pr-creator] PR already created today for ${siteConfig.name}: ${existing.prUrl}`);
    return existing;
  }

  const octokit = await getOctokit();
  const { owner, repo } = parseRepo(siteConfig.github_repo);
  const baseBranch = siteConfig.github_branch || 'main';

  let baseSha;
  try {
    const { data: baseRef } = await octokit.git.getRef({ owner, repo, ref: `heads/${baseBranch}` });
    baseSha = baseRef.object.sha;
    console.log(`[pr-creator] Base branch ${baseBranch} SHA: ${baseSha.slice(0, 10)}...`);
  } catch (err) {
    const detail = err.response?.data?.message || err.message;
    throw new Error(`[pr-creator] Failed to get base branch ref: ${detail}`);
  }

  let branchAlreadyExisted = false;
  try {
    await octokit.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: baseSha });
    console.log(`[pr-creator] Created branch: ${branch}`);
  } catch (err) {
    if (err.status === 422) {
      branchAlreadyExisted = true;
      console.log(`[pr-creator] Branch ${branch} already exists — continuing`);
    } else {
      const detail = err.response?.data?.message || err.message;
      throw new Error(`[pr-creator] Failed to create branch ${branch}: ${detail}`);
    }
  }

  const byFile = {};
  for (const imp of improvements) {
    if (!imp.file) continue;
    if (!byFile[imp.file]) byFile[imp.file] = [];
    byFile[imp.file].push(imp);
  }

  let filesEdited = 0;

  for (const [filePath, fileImps] of Object.entries(byFile)) {
    const existing = await getFileContent(octokit, owner, repo, filePath, branch);
    if (!existing) {
      console.warn(`[pr-creator] File not found in repo: ${filePath} — skipping`);
      continue;
    }

    let content = existing.content;
    for (const imp of fileImps) {
      content = applyImprovement(content, imp);
    }

    if (content === existing.content) {
      console.warn(`[pr-creator] No textual change applied to ${filePath} — skipping commit`);
      continue;
    }

    const commitMsg = `[Cultivai] ${today}: ${fileImps.map((i) => i.type).join(', ')} in ${filePath}`;

    try {
      await octokit.repos.createOrUpdateFileContents({
        owner, repo, path: filePath, message: commitMsg,
        content: Buffer.from(content).toString('base64'),
        sha: existing.sha, branch,
      });
    } catch (err) {
      const detail = err.response?.data?.message || err.message;
      throw new Error(`[pr-creator] Failed to commit ${filePath}: ${detail}`);
    }
    filesEdited++;
  }

  if (filesEdited === 0) {
    try { await octokit.git.deleteRef({ owner, repo, ref: `heads/${branch}` }); } catch {}
    console.log(`[pr-creator] No file edits applied for ${siteConfig.name} — branch deleted.`);
    return { skipped: true, reason: 'no_edits' };
  }

  let pr;
  try {
    const { data } = await octokit.pulls.create({
      owner, repo, title: prTitle, body: prBody, head: branch, base: baseBranch,
    });
    pr = data;
  } catch (err) {
    const detail = err.response?.data?.message || err.message;
    throw new Error(`[pr-creator] Failed to create PR: ${detail}`);
  }

  console.log(`[pr-creator] PR created: ${pr.html_url}`);

  const result = {
    site: siteConfig.name, date: today, prNumber: pr.number,
    prUrl: pr.html_url, branch, filesEdited, improvements: improvements.length,
  };
  fs.writeFileSync(outFile, JSON.stringify(result, null, 2));
  return result;
}

module.exports = { run, buildPrBody, applyImprovement, shortHash };
